#!/bin/bash

# One of the following: xrandr, xbacklight, kernel
METHOD="xrandr"

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  light -A 25
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
  light -U 25
fi
PERCENT=$(light)
echo "${PERCENT:0:-3}%"
