#!/bin/bash

bumblebee_modules = ''

if [ -e '/sys/class/thermal/thermal_zone0/temp' ]; then
	bumblebee_modules+='sensors '
fi


if $(lspci -k | grep -q "GeForce"); then
	bumblebee_modules+='nvidiagpu '
fi

bumblebee_modules+='nic traffic cpu memory '

if [ -e '/sys/class/power_supply/BATTERY0' ]; then 
	bumblebee_modules+='battery '
fi

bumblebee_modules+='github date time pasink pasource'

$(find ~/.antigen | grep /bumblebee-status/bumblebee-status) -m $bumblebee_modules  -t solarized-powerline

